# -*- coding: utf-8 -*-
"""SimpleRNNtounderstand.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XxWGkAf2Qt73A81GFkPsl9cSYPql4PUg
"""

from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense, SimpleRNN,Embedding,Flatten
from keras.preprocessing.sequence import pad_sequences

(x_train,y_train),(x_test,y_test)=imdb.load_data()

x_train

x_train[0]

#len of the review
len(x_train[0])

len(x_train[1])

x_train=pad_sequences(x_train,padding='post',maxlen=50)
x_test= pad_sequences(x_test,padding='post', maxlen=50)

x_train.shape

model=Sequential()

model.add(SimpleRNN(32,input_shape=(50,1),return_sequences=False))
model.add(Dense(1,activation='sigmoid'))

model.summary()

model.compile(loss='binary_crossentropy',metrics=['accuracy'],optimizer='Adam')

model.fit(x_train,y_train,epochs=10,validation_data=(x_test,y_test))